type: custom:apexcharts-card
header:
  show: true
  title: EDF Freephase Prices
show:
  last_updated: true
now:
  show: false
  label: now
graph_span: 48h
span:
  start: day
  offset: "-1h"
series:
  - entity: sensor.edf_freephase_prices
    data_generator: |
      let prices = entity.attributes.array;
      let ends = prices.length-1;
      let final = prices.map((item, index) => {
        return [item.from, item.price];
      });
      final.push([prices[ends].upto, prices[ends].price]);
      return final;
    curve: stepline
    name: Import
    show:
      legend_value: false
      extremas: true
    stroke_width: 2
    color: red
apex_config:
  annotations:
    yaxis:
      - "y": 23.16
        borderColor: red
        label:
          text: Ref
          borderWidth: 0
          style:
            background: "#0000"
    xaxis:
      - x: EVAL:new Date().setHours(16,0,0)
        x2: EVAL:new Date().setHours(19,0,0)
        fillColor: "#FEB019"
        label:
          text: Peak
          borderWidth: 0
          style:
            background: "#0000"
      - x: EVAL:new Date(Date.now()-86400000).setHours(23,0,0)
        x2: EVAL:new Date().setHours(6,0,0)
        fillColor: "#B3F7CA"
        label:
          text: Cheap
          borderWidth: 0
          style:
            background: "#0000"
      - x: EVAL:new Date(Date.now()+86400000).setHours(16,0,0)
        x2: EVAL:new Date(Date.now()+86400000).setHours(19,0,0)
        fillColor: "#FEB019"
        label:
          text: Peak
          borderWidth: 0
          style:
            background: "#0000"
      - x: EVAL:new Date(Date.now()).setHours(23,0,0)
        x2: EVAL:new Date(Date.now()+86400000).setHours(6,0,0)
        fillColor: "#B3F7CA"
        label:
          text: Cheap
          borderWidth: 0
          style:
            background: "#0000"
      - x: EVAL:Math.floor(Date.now()/1800000)*1800000
        label:
          text: Now
          position: bottom
          borderWidth: 1
yaxis:
  - min: 0
